### ISSUE TITLE
Release latest version (0.0.3?) to PyPi

### ISSUE THREAD

**Issue by EmilStenstrom** [micktwomey/pytest-circleci#10]
Hi!

It seems the latest version of pytest-circleci in PyPi is 0.0.2, but there are fixes here that are not in that version. Python 3 compatibility is something we need! Would you mind releasing a new version with the newest master to pypi?

Thanks for this library! :)

**Comment by jayvdb** [comment]
Is this plugin still useful with Circle CI 2.0?

**Comment by joekohlsdorf** [comment]
@jayvdb Why wouldn't it be? Nothing has changed in regard to running Python tests.

**Comment by EmilStenstrom** [comment]
Isn’t this change (https://github.com/micktwomey/pytest-circleci/commit/0e485751bc8e13076699ca42b14c1bd5f00d9074) related to getting the plugin to work with python 3?

**Comment by EmilStenstrom** [comment]
I might have misunderstood things completely here, it was many months ago after all :)

**Comment by micktwomey** [comment]
I've released 0.0.3, apologies for lack of activity, I don't use CircleCI much at the moment and I don't check my github very often.
