### ISSUE TITLE
Smarter test rebalancing

### ISSUE THREAD

**Issue by JBKahn** [micktwomey/pytest-circleci#8]
How would you feel about adding something a bit smarter to this package as an option. Where if you give the name of the `xml` output files in the containers it will get the previous builds artifacts and have a simple bin packing algorithm (like sort by time and add to the smallest total time bucket) based on those timings.

I'd be happy to help with this.

**Comment by r3m0t** [comment]
You can use CircleCI's built-in parallelisation? Specify the filenames with a glob pattern in `circle.yml` and it does as you suggest.

**Comment by ryanwilsonperkin** [comment]
Hey @JBKahn, I was pretty excited about that idea too so I've written https://github.com/ryanwilsonperkin/pytest-circleci-parallelized to handle this. Rather than reimplementing the bin packing algorithm though, it just leverages the builtin `circleci test split` command.
